version: "3.7"
services:
  mariadb:
    image: "mariadb:10.9"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=alquilerCoches
    volumes:
      - exampledb:/var/lib/mysql
      - ./db/alquiler.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/app
    ports:
      - 3000:3000
    links:
      - mariadb
  debug-app:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "${PORT}:${PORT}"
    security_opt:
      - "seccomp:unconfined"
    tty: true
    stdin_open: true
    volumes:
      - ./src/:/app
    command: dlv debug --headless --listen=:${PORT} --api-version=2 --log ${MAIN_FILE}

volumes:
  exampledb: {}